# Generated by Django 6.0 on 2025-12-22 02:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='签到系统', max_length=100, verbose_name='站点标题')),
                ('site_logo', models.ImageField(blank=True, null=True, upload_to='system/logo/', verbose_name='站点Logo')),
                ('technician_contact', models.CharField(blank=True, max_length=100, verbose_name='技术支持联系方式')),
                ('installed', models.BooleanField(default=False, verbose_name='是否已安装')),
                ('db_host', models.CharField(blank=True, max_length=100, verbose_name='数据库地址')),
                ('db_name', models.CharField(blank=True, max_length=100, verbose_name='数据库名称')),
                ('db_user', models.CharField(blank=True, max_length=100, verbose_name='数据库用户名')),
            ],
            options={
                'verbose_name': '系统配置',
                'verbose_name_plural': '系统配置',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('student_id', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^\\d{10}$', '学号必须是10位数字')], verbose_name='学号')),
                ('first_name', models.CharField(blank=True, max_length=50, verbose_name='姓名')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('is_staff', models.BooleanField(default=False, verbose_name='后台管理员')),
                ('is_admin', models.BooleanField(default=False, verbose_name='系统管理员')),
                ('first_login', models.BooleanField(default=True, verbose_name='首次登录')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='上次登录时间')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'ordering': ['-created_at'],
            },
        ),
    ]
