# Generated by Django 6.0 on 2025-12-22 03:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='student_id',
            field=models.CharField(max_length=23, unique=True, validators=[django.core.validators.RegexValidator('^\\d{4,23}$', '学号必须是4-23位数字')], verbose_name='学号'),
        ),
    ]
