# Generated by Django 6.0 on 2025-12-22 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_customuser_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='map_api_key',
            field=models.CharField(blank=True, max_length=200, verbose_name='地图 API Key'),
        ),
    ]
