# Generated by Django 6.0 on 2025-12-22 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_systemconfig_map_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='password_length',
            field=models.PositiveSmallIntegerField(default=12, verbose_name='初始密码长度'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='password_require_digits',
            field=models.BooleanField(default=True, verbose_name='包含数字'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='password_require_lowercase',
            field=models.BooleanField(default=True, verbose_name='包含小写字母'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='password_require_symbols',
            field=models.BooleanField(default=True, verbose_name='包含符号'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='password_require_uppercase',
            field=models.BooleanField(default=True, verbose_name='包含大写字母'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='password_symbols',
            field=models.CharField(blank=True, default='!@#$%^&*', max_length=50, verbose_name='符号字符集合'),
        ),
    ]
