# Generated by Django 6.0 on 2025-12-22 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_systemconfig_password_length_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='language_code',
            field=models.CharField(default='zh-hans', max_length=20, verbose_name='界面语言'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='timezone_str',
            field=models.CharField(default='Asia/Shanghai', max_length=50, verbose_name='时区'),
        ),
    ]
