# Generated by Copilot on 2025-12-24
from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ('core', '0005_systemconfig_language_code_systemconfig_timezone_str'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='map_provider',
            field=models.CharField(max_length=20, blank=True, default='', verbose_name='地图 API 提供商'),
        ),
    ]
