# Generated by Django 6.0 on 2025-12-24 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_systemconfig_map_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='map_security_key',
            field=models.CharField(blank=True, max_length=200, verbose_name='地图安全密钥'),
        ),
    ]
