# Generated by Django 6.0 on 2025-12-25 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_is_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='custom_footer',
            field=models.TextField(blank=True, help_text='支持 HTML 标签', verbose_name='自定义页脚'),
        ),
    ]
