# Generated by Django 6.0 on 2025-12-25 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_systemconfig_custom_footer'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='username_display_mode',
            field=models.CharField(choices=[('student_id', '仅学号'), ('name', '仅姓名'), ('both', '学号+姓名')], default='student_id', help_text='控制界面中用户身份的显示方式', max_length=20, verbose_name='用户名显示模式'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='username_masking_mode',
            field=models.CharField(choices=[('none', '不脱敏'), ('frontend', '仅前台脱敏'), ('both', '前台和后台均脱敏')], default='frontend', help_text='控制是否对学号和姓名进行中间部分脱敏处理', max_length=20, verbose_name='用户名脱敏模式'),
        ),
    ]
