# Generated by Django 6.0 on 2025-12-26 10:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_student_id_to_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=23, unique=True, validators=[django.core.validators.RegexValidator('^\\d{4,23}$', '用户名必须是4-23位数字')], verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='username_display_mode',
            field=models.CharField(choices=[('username', '仅用户名'), ('name', '仅姓名'), ('both', '用户名+姓名')], default='username', help_text='控制界面中用户身份的显示方式', max_length=20, verbose_name='用户名显示模式'),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='username_masking_mode',
            field=models.CharField(choices=[('none', '不脱敏'), ('frontend', '仅前台脱敏'), ('both', '前台和后台均脱敏')], default='frontend', help_text='控制是否对用户名和姓名进行中间部分脱敏处理', max_length=20, verbose_name='用户名脱敏模式'),
        ),
    ]
