# Generated by Django 6.0 on 2025-12-22 04:10

import checkin.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='location_enabled',
            field=models.BooleanField(default=False, verbose_name='启用位置限制'),
        ),
        migrations.AddField(
            model_name='activity',
            name='location_lat',
            field=models.FloatField(blank=True, null=True, verbose_name='纬度'),
        ),
        migrations.AddField(
            model_name='activity',
            name='location_lng',
            field=models.FloatField(blank=True, null=True, verbose_name='经度'),
        ),
        migrations.AddField(
            model_name='activity',
            name='location_radius_m',
            field=models.PositiveIntegerField(default=0, verbose_name='范围(米)'),
        ),
        migrations.AddField(
            model_name='activity',
            name='qr_enabled',
            field=models.BooleanField(default=False, verbose_name='启用二维码'),
        ),
        migrations.AddField(
            model_name='activity',
            name='qr_refresh_interval_s',
            field=models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(10)], verbose_name='二维码刷新周期(秒)'),
        ),
        migrations.AddField(
            model_name='activity',
            name='qr_secret',
            field=models.CharField(default=checkin.models.generate_qr_secret, max_length=32, verbose_name='二维码密钥'),
        ),
        migrations.AddField(
            model_name='activity',
            name='repeat_type',
            field=models.CharField(choices=[('none', '不重复'), ('daily', '每日'), ('weekly', '每周')], default='none', max_length=10, verbose_name='重复方式'),
        ),
        migrations.AddField(
            model_name='activity',
            name='repeat_weekdays',
            field=models.JSONField(default=list, verbose_name='每周重复日(1-7)'),
        ),
        migrations.AddField(
            model_name='activity',
            name='window_end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='每日结束时刻'),
        ),
        migrations.AddField(
            model_name='activity',
            name='window_start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='每日开始时刻'),
        ),
        migrations.AddField(
            model_name='checkinrecord',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='签到纬度'),
        ),
        migrations.AddField(
            model_name='checkinrecord',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='签到经度'),
        ),
    ]
